#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /authentication_token
    methods: ['POST']

docs:
    path: /api/docs

index:
    path: /
    controller: App\Controller\IndexController::index
